import "./globals.css";
import { satoshi } from "./fonts";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
